site_name: Bottinelli Informatica - Documentazione interna
repo_url: https://github.com/Bottinelli-Informatica/Bottinelli-Informatica.github.io.git
site_url: https://github.com/Bottinelli-Informatica/Bottinelli-Informatica.github.io.git

nav:
    - Home:  index.md
    - Opla:
      - Clienti: opla/anagrafica clienti.md
      - Dispo tessitura: opla/dispo tessitura orditura.md
      - Dispo lavorazione: opla/dispo lavorazione.md 
    - Procedure:
      - Disposizione campione tessitura: procedure/Procedura disposizione campione tessitura.md
      - Disposizione campione stampa: procedure/Procedura disposizione campione stampa.md
    
markdown_extensions:
    - toc:
        toc_depth: 4    
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
             - name: mermaid
               class: mermaid
               format: !!python/name:pymdownx.superfences.fence_code_format
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg    
    - md_in_html 
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences   
    - pymdownx.tabbed:
        alternate_style: true
    - tables
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde  
    - pymdownx.blocks.caption    

theme:
  name: material
  logo: img/logo_bottinelli_vector_RGB.png
  icon:
    repo: fontawesome/brands/gitlab
  favicon: img/logo_bottinelli.png 
  features:
    - navigation.instant
    - navigation.instant.progress    
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.tooltips

    
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
   
plugins:
  - search:
      lang: it
      separator: '[\s\-\.\_]+'
  - privacy      
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true  
    
extra_css:
  - stylesheets/extra.css  

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js  

copyright: >
  Copyright &copy; 2025 - 2030 Bottinelli Informatica –
  <a href="#__consent">Change cookie settings</a>
  
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage   
    